version: '3'

services:
  bitcoind:
    image: gcr.io/hc-public/bitcoind:0.1.0
    ports:
      - "19000:19000"
      - "19001:19001"
  bitgo:
    build: .
    ports:
      - "19332:19332"
    depends_on:
      - bitcoind
